### PR TITLE
Hydrolocation implementation

### LINKED ISSUE #14: Implement Hydro Location
To support linking observations to a nexus, this should be done via a `HydroLocation` association realizing the abstract nexus.
The relevant HY Features concept is represented [here](http://docs.opengeospatial.org/is/14-111r6/14-111r6.html#figure35).

The nexus itself should remain a conceptual, topological feature, and the connection to observation data is made via the hydro location.  This would invalidate the `Observation_Point` subclass of nexus, and migrate the functionality to a (most likely) sub type of hydro location.

### PR DESCRIPTION
**Pull request by hellkite500**
Closes #14 

## Additions

- Added `HydroLocation`, `HydroLocationType`, `NWISLocation`

## Removals

- `Observation_Point`

## Testing

1. Minimal test coverage for new additions, all tests new and existing passing

## Notes

- `nwis_location.py` requires an `nwis_client` and `_restclient` module that currently exist in a linked private repository.  NOAA-OWP organization members with configured ssh/auth should be able to install these modules via the `requirements.txt` files without issue, but this is a current major limitation for general use.

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

**Comment by hellkite500** [comment]
I think at least one constructor is missing a meaningful docstring.  I'll try to clean that up and any other inline documentation that I see is lacking.  Feel free to call out any places you see in review that I can make this better!

**Comment by jdmattern-noaa** [comment]
@hellkite500 Is it expected for the 3 python builds to fail right now when trying to clone the eval tools nwis client?

**Comment by hellkite500** [comment]
Yeah, they are in a private repo, so unless you have an auth key
configured, it may not work.

**Comment by jdmattern-noaa** [comment]
I have the NWIS tests passing in locally in my CentOS 7 VM.

**Review by jdmattern-noaa — APPROVED** [review]
Looks good to me. I added docstring params to the nwis_location class and fixed the file name.

**Pull request merged**
